ToolRentalWebApplication/Areas/Admin/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ToolRentalWebApplication.Data;
using ToolRentalWebApplication.Entities;

namespace ToolRentalWebApplication.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BranchController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BranchController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Branch
        public async Task<IActionResult> Index()
        {
            return View(await _context.Branches.ToListAsync());
        }

        // GET: Admin/Branch/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // GET: Admin/Branch/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Branch/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BranchName,BranchAddress,WorkingHours,ThumbnailImagePath,Title")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                _context.Add(branch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // GET: Admin/Branch/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches.FindAsync(id);
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        // POST: Admin/Branch/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BranchName,BranchAddress,WorkingHours,ThumbnailImagePath,Title")] Branch branch)
        {
            if (id != branch.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(branch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchExists(branch.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // GET: Admin/Branch/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // POST: Admin/Branch/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var branch = await _context.Branches.FindAsync(id);
            _context.Branches.Remove(branch);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BranchExists(int id)
        {
            return _context.Branches.Any(e => e.Id == id);
        }
    }
}

ToolRentalWebApplication/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ToolRentalWebApplication.Entities;
using ToolRentalWebApplication.Data;
using Microsoft.AspNetCore.Authorization;

namespace ToolRentalWebApplication.Areas.Admin.Models
{
    [Area("Admin")]
    [Authorize(Roles="Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ThumbnailImagePath")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ThumbnailImagePath")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

ToolRentalWebApplication/Controllers/ToolListController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ToolRentalWebApplication.Models;
using ToolRentalWebApplication.Data;
using ToolRentalWebApplication.Entities;

namespace ToolRentalWebApplication.Controllers
{
    public class ToolListController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public ToolListController(ILogger<HomeController> logger, ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            //IEnumerable<ToolDetailsModel> toolDetailsModels = null;
            var toolDetailsModels = await GetToolDetails(id);
            ViewBag.CategoryId = id;

            return View(toolDetailsModels);
        }
            private async Task<IEnumerable<ToolDetailsModel>> GetToolDetails(int id)
            {
            return await (from tool in _context.Tools
                          join category in _context.Categories
                          on tool.CategoryId equals category.Id
                          join branch in _context.Branches
                          on tool.BranchId equals branch.Id
                          where tool.CategoryId == id 
                          select new ToolDetailsModel
                          {
                              CategoryId = id,
                              CategoryTitle = category.Title,
                              ToolTitle = tool.Title,
                              ToolId = tool.Id,
                              ToolDescription = tool.Description,
                              ThumbnailImagePath = tool.ThumbnailImagePath,
                              PricePerDay = tool.PricePerDay,
                              PricePerHour = tool.PricePerHour,
                              BranchName = branch.BranchName,
                             
                          }).ToListAsync();  
            }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToolRentalWebApplication/Controllers/UserAuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ToolRentalWebApplication.Data;
using ToolRentalWebApplication.Models;

namespace ToolRentalWebApplication.Controllers
{
    public class UserAuthController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;

        public UserAuthController(ApplicationDbContext context,
                                  UserManager<ApplicationUser> userManager,
                                  SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            loginModel.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(loginModel.Email,
                                                                     loginModel.Password,
                                                                     loginModel.RememberMe,
                                                                     lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    loginModel.LoginInValid = "";
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt");
                }

            }
            return PartialView("_UserLoginPartial", loginModel);

        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();

            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser(RegistrationModel registrationModel)
        {
            registrationModel.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    UserName = registrationModel.Email,
                    Email = registrationModel.Email,
                    PhoneNumber = registrationModel.PhoneNumber,
                    FirstName = registrationModel.FirstName,
                    LastName = registrationModel.LastName,
                    Address1 = registrationModel.Address1,
                    Address2 = registrationModel.Address2,
                    PostCode = registrationModel.PostCode

                };

                var result = await _userManager.CreateAsync(user, registrationModel.Password);

                if (result.Succeeded)
                {
                    registrationModel.RegistrationInValid = "";

                    await _signInManager.SignInAsync(user, isPersistent: false);

                    return PartialView("_UserRegistrationPartial", registrationModel);
                }

                AddErrorsToModelState(result);

            }
            return PartialView("_UserRegistrationPartial", registrationModel);

        }

        [AllowAnonymous]
        public async Task<bool> UserNameExists(string userName)
        {
            bool userNameExists = await _context.Users.AnyAsync(u => u.UserName.ToUpper() == userName.ToUpper());

            if (userNameExists)
                return true;

            return false;

        }

        private void AddErrorsToModelState(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }
    }
}

ToolRentalWebApplication/Views/Shared/_AdminMenuPartial.cshtml
@using ToolRentalWebApplication.Data
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
    <li class="nav-item dropdown show">
        <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">Admin</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
            <a class="dropdown-item" href="#">Customers</a>
            <a class="dropdown-item" asp-area="Admin" asp-controller="Branch" asp-action="Index">Branches</a>
            <a class="dropdown-item" href="#">Rentals</a>
            <a class="dropdown-item" href="#">Reservations</a>
        </div>
    </li>
}

ToolRentalWebApplication/Views/Shared/_AuthScriptsPartial.cshtml
<script src="~/js/UserRegistration.js" asp-append-version="true"></script>
<script src="~/js/UserLogin.js" asp-append-version="true"></script>
<script src="~/js/BootstrapAlerts.js" asp-append-version="true"></script>

ToolRentalWebApplication/Views/Shared/_DisplayCardRowPartial.cshtml
@using ToolRentalWebApplication.Entities
@using ToolRentalWebApplication.Data

@model IEnumerable<Category>


    @if (Model.Count() > 0)
    {

        <div class="row mt-3">
            @foreach (Category item in Model)
            {
                <div class="col-md-3 mt-3">
                    <a href="@Url.Action("Index", "ToolList", new { id = item.Id })" class="card-link" data-categoryId="@item.Id">
                        <div class="card">
                            <img class="img-thumbnail" src="@item.ThumbnailImagePath" alt="@item.Title">
                            <div class="card-body">
                                <h5 class="card-title">@item.Title</h5>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    }

ToolRentalWebApplication/Views/Shared/_EmployeeMenuPartial.cshtml
@using ToolRentalWebApplication.Data
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "employeezirmunai") ||
     SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "employeeantakalnis") ||
     SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "employeekaroliniskes"))
{
<li class="nav-item dropdown show">
    <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">Employee</a>
    <div class="dropdown-menu">
        <a class="dropdown-item" asp-area="Employee" asp-controller="Reservation" asp-action="Index">Reservations</a>
        <a class="dropdown-item" asp-area="Employee" asp-controller="Rental" asp-action="Index">Rentals</a>
    </div>
</li>
}

ToolRentalWebApplication/Views/Shared/_HomePageContentPartial.cshtml
@using ToolRentalWebApplication.Entities
@model IEnumerable<Category>
<!--Hero Section-->
<div class="hero section">
    <img class="img-fluid" src="~/Images/HeroImage.jpg">
    <div class="hero-heading">
        <h2 class="hero-heading-text">Rent Tools at <strong>ToolRental</strong></h2>
        <a id="HeroRegisterButton" class="btn btn-outline-info btn-lg text-light hero-register-button" data-toggle="modal" data-target="#UserRegistrationModal">Register</a>
    </div>
</div>

<hr class="section-divider" />

<!--Courses Section-->
<div id="Tools" class="tools section">
    <h3 class="section-header"><i class="fas fa-laptop-code mr-2 text-info"></i>Tools</h3>
    @{
        const int itemsPerRow = 4;

        var count = Model.Count() / itemsPerRow;
        var catList = new List<Category>();

    }
    @for (int i = 0; i <= count; i++)
    {
        catList = Model.Skip(i * itemsPerRow).Take(itemsPerRow).ToList();

        <partial name="_DisplayCardRowPartial" model="catList" />

    }
</div>

<hr class="section-divider" />

<!--Contact Us Section-->

<div id="ContactUs" class="contact-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-phone-alt mr-2 text-info"></i>Contact Us</h3>
    <div class="col-md-5">
        Email us any questions or inquiries or call 555-555-5555. We would be happy to answer your questions and set up a meeting with you.
    </div>
    <div class="mt-3">
        <div class="col-md-8">
            <form>
                <input type="hidden" />
                <div class="form-group">
                    <label for="Name" class="control-label">Name: </label>
                    <input id="Name" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Email" class="control-label">Email: </label>
                    <input id="Email" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Subject" class="control-label">Subject: </label>
                    <input id="Subject" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="MessageBody" class="control-label">Message: </label>
                    <textarea id="Messagebody" cols="30" rows="10" class="form-control"></textarea>

                </div>
                <div class="form-group d-flex">
                    <input type="button" value="Send Email" class="btn btn-outline-info ml-auto" />
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="section-divider" />

<!--About Us Section-->

<div id="AboutUs" class="about-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-chalkboard-teacher mr-2 text-info"></i>About Us</h3>
    <div class="mt-3 mb-5">
        <div class="col-md-5">
            <p>
                <strong>ToolRental</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus augue eros, iaculis sed euismod vitae, bibendum eu nisl. Etiam lectus velit, blandit quis nisl vitae, porttitor fringilla libero. Fusce et aliquam orci. Duis sed dictum ex. Fusce eget tortor lacinia, dignissim eros hendrerit, facilisis magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ex massa, placerat sed ultrices id, auctor quis dui. Donec aliquet porta erat ut viverra.
            </p>
        </div>
    </div>
</div>

ToolRentalWebApplication/Views/Shared/_UserLoginPartial.cshtml
@model ToolRentalWebApplication.Models.LoginModel

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_login">

            </div>
            
            <form id="UserLoginForm" asp-controller="UserAuth" asp-action="Login">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="LoginInValid">
                <div class="form-group row">
                    <label asp-for="Email" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Email" placeholder="Email Address" class="form-control" >
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Password" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Password" placeholder="Password" class="form-control">
                        <span asp-validation-for="Password" class="text-danger"></span>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-8 offset-md-4">
                        <div class="form-check">
                            <input asp-for="RememberMe" class="form-check-input">
                            <label asp-for="RememberMe" class="col-md-4 col-form-label"></label>

                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" id="login" name ="login" class="btn btn-primary">Login</button>
        </div>
    </div>
</div>

ToolRentalWebApplication/Views/Shared/_UserRegistrationPartial.cshtml
@model ToolRentalWebApplication.Models.RegistrationModel

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-user mr-2 text-info"></i>Register</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_register">
            </div>
            <form id="UserRegistrationForm" name="UserRegistrationForm" asp-controller="UserAuth" asp-action="RegisterUser">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="RegistrationInValid">
                <div class="form-group row">
                    <label asp-for="Email" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Email" placeholder="Email Address" class="form-control">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Password" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Password" placeholder="Password" class="form-control">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ConfirmPassword" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="FirstName" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="FirstName" placeholder="First Name" class="form-control">
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="LastName" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="LastName" placeholder="Last Name" class="form-control">
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Address1" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Address1" placeholder="Address1" class="form-control">
                        <span asp-validation-for="Address1" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Address2" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Address2" placeholder="Address2" class="form-control">
                        <span asp-validation-for="Address2" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PostCode" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="PostCode" placeholder="Post Code" class="form-control">
                        <span asp-validation-for="PostCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PhoneNumber" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="PhoneNumber" placeholder="Phone Number" class="form-control">
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <div class="form-check">
                            <input asp-for="AcceptUserAgreement" class="form-check-input">
                            <label asp-for="AcceptUserAgreement" class="form-check-label">I accept the <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a></label>
                        </div>
                    </div>
                </div>
                <input type="hidden" asp-for="CategoryId" />
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button id="register" name="register" type="button" class="btn btn-primary">Register</button>
        </div>
    </div>
</div>